import os

SECRET_KEY = os.environ.get("SECRET_KEY") or os.urandom(32)

SQLALCHEMY_DATABASE_URI = "sqlite:///db.sqlite"
SESSION_COOKIE_NAME = 'flask_socketio_session'

# ! DEBUG
DEBUG_MODE = 0
DEBUG_MODE_PLAYERS = 0
DEBUG_MODE_TALKS = 0
DEBUG_MODE_TABLE_CARDS = 0
DEBUG_MODE_END_GAME = 0
DEBUG_MODE_FAKE_ROUNDS= 0
DEBUG_MODE_FAKE_BELOTE = -1